export const colors = {
  bg: '#0a0a0a',
  surface: '#111',
  surface2: '#1a1a1a',
  surface3: '#1a1a2e',
  border: '#222',
  border2: '#333',
  text: '#e0e0e0',
  textMuted: '#888',
  textDim: '#666',
  textFaint: '#555',
  textGhost: '#444',
  white: '#fff',
  accent: '#0a84ff',
  green: '#34c759',
  red: '#ff3b30',
  orange: '#ff9f0a',
  purple: '#a78bfa',
  teal: '#34d399',
  errorBg: '#2d1515',
  errorText: '#ff6b6b',
} as const;

export const fonts = {
  system: "-apple-system, BlinkMacSystemFont, 'SF Pro', system-ui, sans-serif",
  mono: "'SF Mono', 'Fira Code', 'Consolas', monospace",
} as const;

export const globalStyles = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { overflow: hidden; }
  input, textarea, button { -webkit-appearance: none; }
  ::-webkit-scrollbar { width: 4px; }
  ::-webkit-scrollbar-thumb { background: #333; border-radius: 2px; }
`;

export const styles = {
  app: {
    display: 'flex',
    flexDirection: 'column' as const,
    height: '100dvh',
    backgroundColor: colors.bg,
    color: colors.text,
    fontFamily: fonts.system,
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    borderBottom: `1px solid ${colors.surface2}`,
    flexShrink: 0,
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  headerTitle: {
    fontSize: '17px',
    fontWeight: 600,
    color: colors.white,
  },
  statusDot: (connected: boolean) => ({
    width: 8,
    height: 8,
    borderRadius: '50%',
    backgroundColor: connected ? colors.green : colors.red,
    display: 'inline-block',
    marginRight: 8,
  }),
  menuBtn: {
    padding: '6px 10px',
    borderRadius: '8px',
    border: `1px solid ${colors.border2}`,
    backgroundColor: 'transparent',
    color: '#aaa',
    fontSize: '14px',
    cursor: 'pointer',
  },
  messages: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '12px 16px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
    WebkitOverflowScrolling: 'touch' as const,
  },
  userMsg: {
    padding: '10px 14px',
    borderRadius: '16px',
    backgroundColor: '#1c3a5e',
    alignSelf: 'flex-end' as const,
    maxWidth: '85%',
    fontSize: '15px',
    lineHeight: '1.4',
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    color: colors.text,
  },
  assistantMsg: {
    padding: '4px 0',
    fontSize: '15px',
    lineHeight: '1.5',
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    color: colors.text,
  },
  toolMsg: {
    padding: '6px 10px',
    borderRadius: '8px',
    backgroundColor: colors.surface3,
    borderLeft: `3px solid ${colors.purple}`,
    fontSize: '13px',
    color: colors.purple,
    fontFamily: fonts.mono,
  },
  systemMsg: {
    padding: '2px 0',
    fontSize: '13px',
    color: '#64748b',
    fontStyle: 'italic' as const,
  },
  errorMsg: {
    padding: '6px 10px',
    borderRadius: '8px',
    backgroundColor: colors.errorBg,
    borderLeft: `3px solid ${colors.errorText}`,
    fontSize: '14px',
    color: colors.errorText,
  },
  inputArea: {
    display: 'flex',
    gap: '8px',
    padding: '12px 16px',
    borderTop: `1px solid ${colors.surface2}`,
    flexShrink: 0,
    paddingBottom: 'max(12px, env(safe-area-inset-bottom))',
  },
  input: {
    flex: 1,
    padding: '10px 16px',
    borderRadius: '20px',
    border: `1px solid ${colors.border2}`,
    backgroundColor: colors.surface2,
    color: colors.text,
    fontSize: '16px',
    outline: 'none',
    fontFamily: 'inherit',
    resize: 'none' as const,
    minHeight: '40px',
    maxHeight: '120px',
  },
  button: (variant: 'send' | 'stop' | 'secondary') => ({
    padding: '10px 16px',
    borderRadius: '20px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '15px',
    fontWeight: 600,
    flexShrink: 0,
    backgroundColor: variant === 'send' ? colors.accent :
                     variant === 'stop' ? colors.red :
                     colors.border2,
    color: colors.white,
  }),
  controls: {
    display: 'flex',
    gap: '8px',
    padding: '0 16px 8px',
    flexShrink: 0,
  },
  // Drawer styles
  drawer: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    width: '300px',
    height: '100dvh',
    backgroundColor: colors.surface,
    borderRight: `1px solid ${colors.border}`,
    zIndex: 100,
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
  },
  overlay: (open: boolean) => ({
    position: 'fixed' as const,
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    zIndex: 99,
    display: open ? 'block' : 'none',
  }),
  drawerHeader: {
    padding: '16px',
    borderBottom: `1px solid ${colors.border}`,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  drawerTitle: {
    fontSize: '16px',
    fontWeight: 600,
    color: colors.white,
  },
  sessionItem: (active: boolean) => ({
    padding: '12px 16px',
    borderBottom: `1px solid ${colors.surface2}`,
    cursor: 'pointer',
    backgroundColor: active ? colors.surface3 : 'transparent',
    borderLeft: active ? `3px solid ${colors.accent}` : '3px solid transparent',
  }),
  sessionLabel: {
    fontSize: '14px',
    fontWeight: 500,
    color: colors.text,
  },
  sessionPreview: {
    fontSize: '12px',
    color: colors.textDim,
    marginTop: '2px',
    overflow: 'hidden' as const,
    textOverflow: 'ellipsis' as const,
    whiteSpace: 'nowrap' as const,
  },
  sessionsList: {
    flex: 1,
    overflowY: 'auto' as const,
  },
  codeBlock: {
    backgroundColor: colors.surface3,
    borderRadius: '6px',
    padding: '8px 12px',
    fontFamily: fonts.mono,
    fontSize: '13px',
    overflowX: 'auto' as const,
    margin: '4px 0',
  },
  inlineCode: {
    backgroundColor: colors.surface3,
    borderRadius: '3px',
    padding: '1px 4px',
    fontFamily: fonts.mono,
    fontSize: '13px',
  },
};
